name: Cron request example
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "00,20,40 14-23 * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: potaesm/github-actions-request@1.0.7
        with:
          url: ${{ secrets.URL }}
          method: get
          auth: ${{ secrets.AUTH }}
