name: Cron request example
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/15 7-19 * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: potaesm/github-actions-request@1.0.5
        with:
          url: ${{ secrets.URL }}
          method: get
          auth: '{"username":"gtz","password":"node"}'