name: Cron request example
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: potaesm/github-actions-request@1.0.2
        with:
          url: ${{ secrets.URL }}
          method: get