name: Cron request example
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: potaesm/github-actions-request@1.0.3
        with:
          url: ${{ secrets.URL }}
          method: get
          auth: "{ username: 'gtz', password: 'node' }"